// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Source: ./template-1.ets

interface User {
  name: string;
}

export function render(users: User[]): string {
  return (() => {
  let result = '';
  users.forEach(function(user) {
  result += 'Name: ';
  result +=  user.name;
  result += '\n';
  })
  return result;
  })()
}
