// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// Source: ./template-2.ets

type Account = {
  name: string;
  needsPasswordReset: boolean;
}
export function render({ name, needsPasswordReset }: Account): string {
let result = '';
result += 'Hello ';
result += name;
result += '!\n';
if (needsPasswordReset) {
result += 'You need to update your password.\n';
}
return result;
}
