/*
 * THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 *
 * Run `npx ets` or `yarn ets` to regenerate this file.
 * Source: ./user-partial.ets
 */
/* eslint-disable */

export interface Props {
  name: string;
  email: string;
  phone: string;
}

export default function (props: Props): string {
  let result = "";
  result += "Name: ";
  result += props.name;
  result += "\nEmail: ";
  result += props.email;
  result += "\nPhone: ";
  result += props.phone;
  return result;
}
