// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.;
// Source: ./template-4.ets

import { uppercase } from './helpers';
export function render(name: string): string {
let result = '';
result += 'Hello ';
result += uppercase(name);
result += '!\n';
return result;
}
