import { trimLagging, trimLeading, sanitizeString } from "./utils";
import { Node, BlockNode, StatementNode, parse } from "../parser";

function isStatementNode(node: Node): node is StatementNode | BlockNode {
  return ["statement", "blockOpen", "blockClose"].includes(node.type);
}

const RESULT = "result";

export const AUTOGENERATED_NOTICE =
  "// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.";

function compile(nodes: Node[]): string {
  let compiled = `${AUTOGENERATED_NOTICE}\n`;

  nodes.forEach((node, idx) => {
    switch (node.type) {
      case "text": {
        let content = node.content;

        const prevNode = nodes[idx - 1];
        if (
          // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
          prevNode &&
          (isStatementNode(prevNode) ||
            (prevNode.type === "expression" && prevNode.context.trimLagging))
        ) {
          content = trimLagging(content);
        }

        const nextNode = nodes[idx + 1];
        if (
          // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
          nextNode &&
          isStatementNode(nextNode)
        ) {
          content = trimLeading(content);
        }

        if (content) {
          compiled += `${RESULT} += '${sanitizeString(content)}';\n`;
        }
        break;
      }
      case "expression": {
        compiled += `${RESULT} += ${node.content};\n`;
        break;
      }
      case "statement": {
        compiled += `${node.content}\n`;
        break;
      }
      case "blockOpen": {
        compiled += `${node.content}\n`;
        if (node.context.isRoot) {
          compiled += `let ${RESULT} = '';\n`;
        }
        break;
      }
      case "blockClose": {
        if (node.context.isRoot) {
          compiled += `return ${RESULT};\n`;
        }
        compiled += `${node.content}\n`;
        break;
      }
      default: {
        const exhaust: never = node;
        return exhaust;
      }
    }
  });
  return compiled;
}

export function compiler(template: string): string {
  return compile(parse(template));
}
