/*
 * THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 *
 * Run `npx ets` or `yarn ets` to regenerate this file.
 * Source: ./template-4.ets
 */
/* eslint-disable */

import { uppercase } from "./helpers";

export interface Props {
  name: string;
}

export default function (props: Props): string {
  let result = "";
  result += "Hello ";
  result += uppercase(props.name);
  result += "!";
  return result;
}
